version: '3.8'

services:
  ansv-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ansv-bot
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-5001}:5001"
    volumes:
      - ./settings.conf:/app/settings.conf:ro
      - ansv-db:/app/messages.db
      - ansv-cache:/app/cache
      - ansv-logs:/app/logs
      - ansv-outputs:/app/static/outputs
      - ansv-voices:/app/voices
    environment:
      - TTS_ENABLED=${TTS_ENABLED:-true}
      - WEB_ENABLED=${WEB_ENABLED:-true}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    command: "${LAUNCH_ARGS:---tts --web}"

  # Optional development container with hot-reload
  ansv-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ansv-dev
    restart: "no"
    ports:
      - "5002:5001"
    volumes:
      - .:/app
    environment:
      - TTS_ENABLED=true
      - WEB_ENABLED=true
      - DEV_MODE=true
    command: "--dev"
    profiles:
      - dev

volumes:
  ansv-db:
  ansv-cache:
  ansv-logs:
  ansv-outputs:
  ansv-voices: